#!/bin/sh

maps_path=$1
temp_map='/temp_map.png'
file="$maps_path$temp_map"


iw=$(file $file|cut -d, -f2|cut -d" " -f2)
ih3=$(file $file|cut -d, -f2|cut -d" " -f4)
ih=$(($ih3/3))

convert $file -gravity North -crop "$iw x $ih+0+0" "$maps_path/crop_1.png"
wait
convert $file -gravity North -crop "$iw x $ih+0+$ih" "$maps_path/crop_2.png"
wait
convert $file -gravity South -crop "$iw x $ih+0+0" "$maps_path/crop_3.png"
